control/files:
 - ascent.mx
 - avtrak-fft.mx
 - bytes-lights-off.mx
 - bytes-lights-on.mx
 - bytes-lights-red.mx
 - bytes-lights-white.mx
 - bytes-sample-00-1m.mx
 - bytes-sample-00-20m.mx
 - bytes-sample-01-1m.mx
 - bytes-sample-01-20m.mx
 - bytes-sample-02-1m.mx
 - bytes-sample-02-20m.mx
 - bytes-sample-03-1m.mx
 - bytes-sample-03-20m.mx
 - bytes-sample-04-1m.mx
 - bytes-sample-04-20m.mx
 - bytes-sample-05-1m.mx
 - bytes-sample-05-20m.mx
 - bytes-sample-06-1m.mx
 - bytes-sample-06-20m.mx
 - bytes-sample-07-1m.mx
 - bytes-sample-07-20m.mx
 - bytes-sample-08-1m.mx
 - bytes-sample-08-20m.mx
 - bytes-sample-09-1m.mx
 - bytes-sample-09-20m.mx
 - bytes-sample-10-1m.mx
 - bytes-sample-10-20m.mx
 - bytes-sample-11-1m.mx
 - bytes-sample-11-20m.mx
 - bytes-sample-12-1m.mx
 - bytes-sample-12-20m.mx
 - bytes-sample-13-1m.mx
 - bytes-sample-13-20m.mx
 - bytes-sample-14-1m.mx
 - bytes-sample-14-20m.mx
 - bytes-sample-15-1m.mx
 - bytes-sample-15-20m.mx
 - bytes-sample-scheduled.mx
 - d5w4r1d.mx
 - dark-5m-white-4m-red-1m-dark.mx
 - init-ms16.mx
 - test-bytes-lights.mx
 - test-grid-aperture-shutter.mx
 - test-lights.mx
 - test-ms16.mx
 - test-predive-sundance.mx
 - test-rehearsal-sundance.mx
 - test-sample-stub.mx
 - test-vertical-sundance.mx
 - test-zcam.mx
 - video_transect.mx
 - video_transect_no_thrust.mx
 - wait.mx
 - zcam-record-standard.mx