project11/platforms/mesobot:
  namespace: /project11/mesobot
  width: 0.5
  length: 2.0
  color:
    red: 1.0
    green: 1.0
    blue: 0.0
  nav_sources:
    usbl:
      geopose_topic: /project11/mesobot/nav/position
